const {chromium} = require('playwright');
const http = require('node:http');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
const files = {'/master.m3u8':'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=100\nlist.m3u8','/list.m3u8':'#EXTM3U\n#EXTINF:1,\na.ts\n#EXTINF:1,\nb.ts\n#EXT-X-ENDLIST','/a.ts':fs.readFileSync(__dirname+'/fixtures/segment0.ts'),'/b.ts':fs.readFileSync(__dirname+'/fixtures/segment1.ts'),'/direct.mp4':Buffer.alloc(65536, 1)};
const hits=[];
const server=http.createServer((req,res)=>{hits.push(req.url);res.setHeader('Access-Control-Allow-Origin','*');if(req.url==='/b.ts'){setTimeout(()=>res.end(files[req.url]),2500);return;} if(req.url==='/direct.mp4'){res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition','attachment; filename=test.mp4');res.setHeader('Content-Length','65536');res.write(files[req.url].subarray(0,32768));setTimeout(()=>res.end(files[req.url].subarray(32768)),5000);return;}res.end(files[req.url]||'');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port;
const extension=require('node:path').resolve(__dirname,'..');
const context=await chromium.launchPersistentContext('',{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],acceptDownloads:true});
try {
let worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
const page=await context.newPage();
const cdp=await context.newCDPSession(page);
await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:fs.mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'tweetfile-test-downloads-'))});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://cdn.tweetfile.com/test-extension',route=>route.fulfill({contentType:'text/html',body:`<html><body><div id="app"><button class="video-row"><span class="video-thumb--folder">Folder</span></button><button class="video-row">Video one</button><button class="video-row">Video two</button></div><script>for(const type of ['pointerdown','pointerup','mousedown','mouseup','click'])window.addEventListener(type,e=>{e.preventDefault();e.stopImmediatePropagation()},true);const item=(name,url,isFolder=false)=>({type:{__name:'VideoRow'},props:{item:{name,url,isFolder,coverImage:''}}});document.querySelector('#app')._vnode={children:[item('Folder','https://cdn.tweetfile.com/never-follow',true),item('Test HLS','${base}/master.m3u8'),item('Direct','${base}/direct.mp4')]};</script></body></html>`}));
await page.goto('https://cdn.tweetfile.com/test-extension');
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader')?.shadowRoot.querySelector('#count').textContent==='2/2');
await page.getByRole('button',{name:'選択解除',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#download').disabled);
await page.getByRole('checkbox',{name:'Test HLS',exact:true}).check();
await page.getByRole('button',{name:'選択した動画を一括ダウンロード',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#progress').value===50);
assert.equal(await page.locator('#tweetfile-downloader').locator('#percent').textContent(),'50%');
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#progress').value===100,{},{timeout:30000});
console.log('STATUS',await page.locator('#tweetfile-downloader').locator('#status').textContent());
const downloads=await worker.evaluate(()=>chrome.downloads.search({}));
assert.equal(downloads.length,1);assert.equal(downloads[0].state,'complete');
assert.ok(downloads[0].filename.endsWith('.mp4'));
assert.equal(fs.readFileSync(downloads[0].filename).toString('ascii',4,8),'ftyp');
assert.ok(!hits.includes('/direct.mp4'));assert.ok(!hits.some(url=>url.includes('never-follow')));
await page.getByRole('button',{name:'全選択',exact:true}).click();
await page.getByRole('checkbox',{name:'Test HLS',exact:true}).uncheck();
await page.getByRole('button',{name:'選択した動画を一括ダウンロード',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#progress').value===50);
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#progress').value===100);
assert.equal(await page.locator('#tweetfile-downloader').locator('#percent').textContent(),'100%');
await page.evaluate(base=>{document.querySelector('#app')._vnode.children.push({type:{__name:'VideoRow'},props:{item:{name:'Added',url:base+'/new.mp4'}}});},base);
await page.waitForFunction(()=>document.querySelector('#tweetfile-downloader').shadowRoot.querySelector('#count').textContent==='2/3');
await page.getByRole('button',{name:'選択一覧を閉じる',exact:true}).click();
assert.equal(await page.locator('#tweetfile-downloader').locator('section').isVisible(),false);
await page.getByRole('button',{name:'動画の選択',exact:true}).click();
await page.setViewportSize({width:390,height:844});
const bounds=await page.locator('#tweetfile-downloader').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);
assert.equal(await page.locator('#tweetfile-downloader').evaluate(el=>getComputedStyle(el).color),'rgb(248, 250, 252)');
assert.deepEqual(errors,[]);
console.log('PASS actual extension: HLS MP4 save, intermediate/final percentages, selection, direct download, folder exclusion, dynamic additions, panel toggle, mobile bounds');
} finally {await context.close();server.close();}
})();
